/* Villa Rudolf na TV — texty ve 4 jazycích.
   Fakta podle villa-rudolf-portal/docs/text-villa-rudolf.md (kap. 3, potvrzeno Pavlem)
   a /info/ na webu. Wi-Fi heslo sem NEPATŘÍ — stránka je veřejná.
   Prázdný řetězec = karta se nezobrazí (např. návod k zapnutí sauny, dokud ho Pavel nedodá). */
window.VR_TEXTY = {
  cs: {
    menu: { home: 'Vítejte', dum: 'Dům', sauna: 'Sauna', bazen: 'Bazén', vylety: 'Výlety', pocasi: 'Počasí', okoli: 'Nákupy a pomoc', mobil: 'Do mobilu' },
    hint: 'Šipkami vybírejte, OK otevře, Zpět vrací.',
    vitejte: 'Vítejte',
    vitejteSub: 'Celá Villa Rudolf je teď jen vaše. Tady najdete vše o domě, sauně, bazénu a výletech po okolí.',
    dnes: 'Dnes',
    dnesSeHodi: 'Dnes se hodí',
    vse: 'Všechny výlety',
    odjezd: 'Odjezd', odjezdV: 'do 10:00',
    klid: 'Noční klid', klidV: 'od 22:00',
    saunaKratce: 'V ceně, bez rezervací',
    saunaNahrati: 'nahřátí asi 30 min',
    bazenOtevreno: 'Otevřeno do 22:00',
    bazenRano: 'Otevírá v 6:00',
    bazenMimo: 'Mimo sezonu',
    bazenMimoV: 'otevíráme v květnu',
    dum: [
      ['clock', 'Příjezd a odjezd', 'Příjezd od 15:00, odjezd do 10:00.'],
      ['moon', 'Noční klid', 'Po 22:00 prosíme o klid kvůli blízkým sousedům. Na zahradě žádné reproduktory a večer žádná hudba. Posezení u ohně do noci je v pořádku.'],
      ['thermo', 'Topení', 'Každý pokoj i každá koupelna má vlastní termostat.'],
      ['kitchen', 'Dvě kuchyně', 'Obě s troubou, myčkou a kompletním nádobím. V přízemí navíc dvě mikrovlnky, vinotéka a kávovar Nespresso, v apartmá Suite mikrovlnka a druhý Nespresso.'],
      ['wash', 'Praní', 'Pračka je v koupelně Pokoje 4 v 1. patře. K dispozici je žehlička, fény jsou v koupelnách.'],
      ['ski', 'Lyžárna', 'V suterénu. Boty v ní přes noc uschnou.'],
      ['grill', 'Altán a grily', 'Altán pro 20 lidí se dvěma velkými elektrickými grily. Grilovat jde i v dešti a ve sněhu.'],
      ['fire', 'Ohniště', 'Ohniště s gabionovou stěnou pro celou partu. Světla na zahradě se po setmění rozsvítí sama.'],
      ['kids', 'Pro děti', 'Hřiště s prolézačkami, skluzavkou, houpačkami a lanovými prvky, trampolína a stolní tenis.'],
      ['car', 'Parkování', 'Zdarma na pozemku za bránou, pohodlně pro 7 aut.'],
      ['bus', 'Skibus', 'Zastávka 200 m od brány, jízda je zdarma. Sjezdovky ve Svobodě 1,9 km, Černá hora a Janské Lázně 4 km.'],
      ['hand', 'Masér', 'Hned vedle domu. Termín vám rádi domluvíme.'],
      ['nosmoke', 'Nekuřácký dům', 'V domě se nekouří. Venku na zahradě klidně.']
    ],
    saunaTitul: 'Finská sauna',
    saunaUvod: 'V suterénu, s předsálím a sprchou. Je jen vaše, v ceně pobytu a bez rezervací.',
    sauna: [
      ['power', 'Zapnutí', 'Saunu zapnete ručně přímo dole v sauně. Na dálku ji zapnout nejde – schválně, kvůli bezpečnosti.'],
      ['clock', 'Nahřátí', 'Sauna se nahřeje zhruba za půl hodiny.'],
      ['shower', 'Před saunou', 'Osprchujte se a osušte. Seďte a lehejte vždy na ručníku.'],
      ['timer', 'Jedno kolo', '8–15 minut, podle toho, jak je vám dobře. Pak se zchlaďte a aspoň stejně dlouho odpočívejte.'],
      ['water', 'Pijte vodu', 'Mezi koly pijte vodu. Alkohol nechte až na potom.'],
      ['kids', 'Děti', 'Děti do sauny jen s dospělým.']
    ],
    doporuceni: 'Doporučujeme',
    riziko: 'Saunu, bazén, trampolínu, hřiště, ohniště i vše ostatní na pozemku používáte na vlastní nebezpečí. Na děti prosím dohlížejte.',
    bazenTitul: 'Bazén',
    bazenUvod: 'Zastřešený a vyhřívaný, večer nasvícený. Dá se zamknout.',
    bazen: [
      ['sun', 'Sezona', 'Od května do konce září. V létě kolem 27 °C, na začátku a na konci sezony bývá voda chladnější.'],
      ['clock', 'Otevřeno', 'Denně 6:00–22:00.'],
      ['lock', 'Zamykání', 'Bazén se dá zamknout. Když u něj nikdo není, zamkněte ho prosím, hlavně kvůli dětem.'],
      ['kids', 'Děti', 'Děti v bazénu jen pod dohledem dospělých.']
    ],
    bazenMimoText: 'Teď je mimo sezonu zavřený. Otevíráme zase v květnu.',
    vyletyTitul: 'Výlety po okolí',
    vyletySub: '{n} ověřených tipů. Vyberte výlet a naskenujte si QR kód do mobilu.',
    filtry: { vse: 'Vše', deti: 'S dětmi', dest: 'Za deště', pesky: 'Pěšky od domu', vyhledy: 'Výhledy a túry', kultura: 'Kultura', voda: 'Koupání', adrenalin: 'Adrenalin' },
    pesky: 'pěšky', autem: 'min autem',
    otevreno: 'Otevírací doba', cena: 'Cena',
    qrMapa: 'Naskenujte telefonem', qrMapaSub: 'trasa v Mapy.cz',
    qrWeb: 'Naskenujte telefonem', qrWebSub: 'web výletu',
    zadneVylety: 'Pro tento výběr teď nic nemáme.',
    pocasiTitul: 'Počasí ve Svobodě nad Úpou',
    pocasiSub: 'Předpověď yr.no, aktualizuje se dvakrát denně.',
    pocasiNic: 'Předpověď se teď nepodařilo načíst.',
    dny: ['neděle', 'pondělí', 'úterý', 'středa', 'čtvrtek', 'pátek', 'sobota'],
    dnyK: ['ne', 'po', 'út', 'st', 'čt', 'pá', 'so'],
    mesice: ['ledna', 'února', 'března', 'dubna', 'května', 'června', 'července', 'srpna', 'září', 'října', 'listopadu', 'prosince'],
    vitr: 'vítr', srazky: 'srážky',
    wx: { clear: 'jasno', fair: 'skoro jasno', partly: 'polojasno', cloudy: 'zataženo', fog: 'mlha', showers: 'přeháňky', rain: 'déšť', snow: 'sníh', sleet: 'déšť se sněhem', thunder: 'bouřky' },
    okoliTitul: 'Nákupy a pomoc',
    nakupy: 'Nákupy', zdravi: 'Lékárna a zdraví', sluzby: 'Palivo',
    overit: 'Otevírací dobu doporučujeme ověřit předem.',
    distWalk: 'pěšky', dist3: '~3 min autem', dist11: '~11 min autem', dist12: '~12 min autem', dist14: '~14 min autem', dist6jl: '~6 min autem · Janské Lázně',
    hDaily22: 'Denně 7:00–22:00', hDaily20: 'Denně 7:00–20:00', hLidl: 'Přibližně 7:00–22:00 denně', hMartin: 'Denně 6:00–20:00',
    hCoop: 'Nonstop, 7 dní v týdnu (mimo dobu s obsluhou samoobslužně)', nMartin: 'Nejbližší obchod, přímo ve Svobodě.',
    hLekarna: 'Po–pá 8:00–12:00 a 13:00–17:00, o víkendu zavřeno', hNemocnice: 'Pohotovost nonstop (i dětská)',
    t112: 'Tísňová linka', v112: 'Jednotné evropské číslo tísňového volání. Funguje i bez kreditu a v cizím jazyce, spojí vás se záchrankou, hasiči i policií.',
    mobilTitul: 'Do mobilu',
    mobilSub: 'Naskenujte QR kód fotoaparátem telefonu.',
    qrPlanovac: 'Plánovač výletů', qrPlanovacSub: 'výlety podle počasí a věku dětí',
    qrInfo: 'Praktické informace', qrInfoSub: 'nákupy, lékárna, kontakty',
    qrApp: 'Aplikace Villa Rudolf', qrAppSub: '',
    offline: 'Bez internetu – zobrazuji uloženou verzi.'
  },

  de: {
    menu: { home: 'Willkommen', dum: 'Das Haus', sauna: 'Sauna', bazen: 'Pool', vylety: 'Ausflüge', pocasi: 'Wetter', okoli: 'Einkaufen & Hilfe', mobil: 'Aufs Handy' },
    hint: 'Mit den Pfeiltasten wählen, OK öffnet, Zurück schließt.',
    vitejte: 'Willkommen',
    vitejteSub: 'Die ganze Villa Rudolf gehört jetzt euch. Hier findet ihr alles zum Haus, zur Sauna, zum Pool und zu Ausflügen in der Umgebung.',
    dnes: 'Heute',
    dnesSeHodi: 'Heute passt gut',
    vse: 'Alle Ausflüge',
    odjezd: 'Abreise', odjezdV: 'bis 10:00',
    klid: 'Nachtruhe', klidV: 'ab 22:00',
    saunaKratce: 'Inklusive, ohne Reservierung',
    saunaNahrati: 'Aufheizen ca. 30 Min.',
    bazenOtevreno: 'Geöffnet bis 22:00',
    bazenRano: 'Öffnet um 6:00',
    bazenMimo: 'Außerhalb der Saison',
    bazenMimoV: 'wir öffnen im Mai',
    dum: [
      ['clock', 'Anreise und Abreise', 'Anreise ab 15:00, Abreise bis 10:00.'],
      ['moon', 'Nachtruhe', 'Ab 22:00 bitte Ruhe – wir haben nahe Nachbarn. Im Garten keine Lautsprecher und abends keine Musik. Am Feuer bis spät zusammensitzen ist in Ordnung.'],
      ['thermo', 'Heizung', 'Jedes Zimmer und jedes Bad hat ein eigenes Thermostat.'],
      ['kitchen', 'Zwei Küchen', 'Beide mit Backofen, Spülmaschine und komplettem Geschirr. Im Erdgeschoss zusätzlich zwei Mikrowellen, Weinkühlschrank und Nespresso, im Apartment Suite Mikrowelle und ein zweiter Nespresso.'],
      ['wash', 'Wäsche', 'Die Waschmaschine steht im Bad von Zimmer 4 im 1. Stock. Ein Bügeleisen ist da, Föhns sind in den Bädern.'],
      ['ski', 'Skiraum', 'Im Untergeschoss. Die Schuhe trocknen dort über Nacht.'],
      ['grill', 'Pavillon und Grills', 'Pavillon für 20 Personen mit zwei großen Elektrogrills. Grillen geht auch bei Regen und Schnee.'],
      ['fire', 'Feuerstelle', 'Feuerstelle mit Gabionenwand für die ganze Gruppe. Die Gartenbeleuchtung schaltet sich bei Dunkelheit selbst ein.'],
      ['kids', 'Für Kinder', 'Spielplatz mit Klettergerüst, Rutsche, Schaukeln und Seilelementen, Trampolin und Tischtennis.'],
      ['car', 'Parken', 'Kostenlos auf dem Grundstück hinter dem Tor, bequem für 7 Autos.'],
      ['bus', 'Skibus', 'Haltestelle 200 m vom Tor, kostenlos. Pisten in Svoboda 1,9 km, Černá hora und Janské Lázně 4 km.'],
      ['hand', 'Masseur', 'Gleich neben dem Haus. Einen Termin vereinbaren wir gern für euch.'],
      ['nosmoke', 'Nichtraucherhaus', 'Im Haus wird nicht geraucht. Draußen im Garten gern.']
    ],
    saunaTitul: 'Finnische Sauna',
    saunaUvod: 'Im Untergeschoss, mit Vorraum und Dusche. Nur für euch, im Preis inbegriffen, ohne Reservierung.',
    sauna: [
      ['power', 'Einschalten', 'Die Sauna wird von Hand direkt unten in der Sauna eingeschaltet. Aus der Ferne geht das bewusst nicht – aus Sicherheitsgründen.'],
      ['clock', 'Aufheizen', 'Die Sauna ist in etwa einer halben Stunde warm.'],
      ['shower', 'Vor der Sauna', 'Duschen und abtrocknen. Immer auf einem Handtuch sitzen und liegen.'],
      ['timer', 'Ein Saunagang', '8–15 Minuten, je nach Wohlbefinden. Danach abkühlen und mindestens genauso lange ruhen.'],
      ['water', 'Wasser trinken', 'Zwischen den Gängen Wasser trinken. Alkohol lieber erst danach.'],
      ['kids', 'Kinder', 'Kinder nur mit Erwachsenen in die Sauna.']
    ],
    doporuceni: 'Unsere Empfehlungen',
    riziko: 'Sauna, Pool, Trampolin, Spielplatz, Feuerstelle und alles andere auf dem Grundstück nutzt ihr auf eigene Gefahr. Bitte achtet auf die Kinder.',
    bazenTitul: 'Pool',
    bazenUvod: 'Überdacht und beheizt, abends beleuchtet. Er lässt sich abschließen.',
    bazen: [
      ['sun', 'Saison', 'Von Mai bis Ende September. Im Sommer um 27 °C, zu Beginn und Ende der Saison ist das Wasser meist kühler.'],
      ['clock', 'Geöffnet', 'Täglich 6:00–22:00.'],
      ['lock', 'Abschließen', 'Der Pool lässt sich abschließen. Wenn niemand dort ist, bitte abschließen – vor allem wegen der Kinder.'],
      ['kids', 'Kinder', 'Kinder im Pool nur unter Aufsicht von Erwachsenen.']
    ],
    bazenMimoText: 'Jetzt außerhalb der Saison geschlossen. Wir öffnen wieder im Mai.',
    vyletyTitul: 'Ausflüge in der Umgebung',
    vyletySub: '{n} geprüfte Tipps. Ausflug wählen und den QR-Code mit dem Handy scannen.',
    filtry: { vse: 'Alle', deti: 'Mit Kindern', dest: 'Bei Regen', pesky: 'Zu Fuß ab Haus', vyhledy: 'Aussichten & Touren', kultura: 'Kultur', voda: 'Baden', adrenalin: 'Adrenalin' },
    pesky: 'zu Fuß', autem: 'Min. mit dem Auto',
    otevreno: 'Öffnungszeiten', cena: 'Preis',
    qrMapa: 'Mit dem Handy scannen', qrMapaSub: 'Route in Mapy.cz',
    qrWeb: 'Mit dem Handy scannen', qrWebSub: 'Website',
    zadneVylety: 'Für diese Auswahl haben wir gerade nichts.',
    pocasiTitul: 'Wetter in Svoboda nad Úpou',
    pocasiSub: 'Vorhersage von yr.no, zweimal täglich aktualisiert.',
    pocasiNic: 'Die Vorhersage konnte gerade nicht geladen werden.',
    dny: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
    dnyK: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
    mesice: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
    vitr: 'Wind', srazky: 'Niederschlag',
    wx: { clear: 'klar', fair: 'heiter', partly: 'teils bewölkt', cloudy: 'bewölkt', fog: 'Nebel', showers: 'Schauer', rain: 'Regen', snow: 'Schnee', sleet: 'Schneeregen', thunder: 'Gewitter' },
    okoliTitul: 'Einkaufen & Hilfe',
    nakupy: 'Einkaufen', zdravi: 'Apotheke & Gesundheit', sluzby: 'Tankstelle',
    overit: 'Wir empfehlen, die Öffnungszeiten vorab zu prüfen.',
    distWalk: 'zu Fuß', dist3: '~3 Min. mit dem Auto', dist11: '~11 Min. mit dem Auto', dist12: '~12 Min. mit dem Auto', dist14: '~14 Min. mit dem Auto', dist6jl: '~6 Min. mit dem Auto · Janské Lázně',
    hDaily22: 'Täglich 7:00–22:00', hDaily20: 'Täglich 7:00–20:00', hLidl: 'Ca. 7:00–22:00 täglich', hMartin: 'Täglich 6:00–20:00',
    hCoop: 'Rund um die Uhr, 7 Tage (außerhalb der bedienten Zeiten Selbstbedienung)', nMartin: 'Das nächste Geschäft, direkt in Svoboda.',
    hLekarna: 'Mo–Fr 8:00–12:00 & 13:00–17:00, am Wochenende geschlossen', hNemocnice: 'Notaufnahme rund um die Uhr (auch für Kinder)',
    t112: 'Notruf', v112: 'Die einheitliche europäische Notrufnummer. Funktioniert auch ohne Guthaben und mehrsprachig – Rettungsdienst, Feuerwehr und Polizei.',
    mobilTitul: 'Aufs Handy',
    mobilSub: 'QR-Code mit der Handykamera scannen.',
    qrPlanovac: 'Ausflugsplaner', qrPlanovacSub: 'Ausflüge nach Wetter und Alter der Kinder',
    qrInfo: 'Praktische Infos', qrInfoSub: 'Einkaufen, Apotheke, Kontakte',
    qrApp: 'App Villa Rudolf', qrAppSub: '',
    offline: 'Kein Internet – gespeicherte Version.'
  },

  en: {
    menu: { home: 'Welcome', dum: 'The house', sauna: 'Sauna', bazen: 'Pool', vylety: 'Trips', pocasi: 'Weather', okoli: 'Shops & help', mobil: 'To your phone' },
    hint: 'Use the arrows to choose, OK to open, Back to return.',
    vitejte: 'Welcome',
    vitejteSub: 'The whole of Villa Rudolf is yours now. Here you will find everything about the house, the sauna, the pool and trips nearby.',
    dnes: 'Today',
    dnesSeHodi: 'Good for today',
    vse: 'All trips',
    odjezd: 'Check-out', odjezdV: 'by 10:00',
    klid: 'Quiet hours', klidV: 'from 22:00',
    saunaKratce: 'Included, no booking',
    saunaNahrati: 'heats up in ~30 min',
    bazenOtevreno: 'Open until 22:00',
    bazenRano: 'Opens at 6:00',
    bazenMimo: 'Out of season',
    bazenMimoV: 'we open in May',
    dum: [
      ['clock', 'Check-in and check-out', 'Check-in from 15:00, check-out by 10:00.'],
      ['moon', 'Quiet hours', 'Please keep it quiet after 22:00 – we have close neighbours. No speakers in the garden and no music in the evening. Sitting and talking by the fire late is fine.'],
      ['thermo', 'Heating', 'Every room and every bathroom has its own thermostat.'],
      ['kitchen', 'Two kitchens', 'Both with oven, dishwasher and full tableware. The ground floor adds two microwaves, a wine fridge and a Nespresso; the Suite has a microwave and a second Nespresso.'],
      ['wash', 'Laundry', 'The washing machine is in the bathroom of Room 4 on the 1st floor. There is an iron; hair dryers are in the bathrooms.'],
      ['ski', 'Ski room', 'In the basement. Boots dry there overnight.'],
      ['grill', 'Gazebo and grills', 'Gazebo for 20 people with two large electric grills. You can grill even in rain or snow.'],
      ['fire', 'Fire pit', 'Fire pit with a gabion wall for the whole group. The garden lights switch on by themselves after dark.'],
      ['kids', 'For kids', 'Playground with climbing frame, slide, swings and rope elements, a trampoline and table tennis.'],
      ['car', 'Parking', 'Free on the grounds behind the gate, comfortably for 7 cars.'],
      ['bus', 'Ski bus', 'Stop 200 m from the gate, free of charge. Slopes in Svoboda 1.9 km, Černá hora and Janské Lázně 4 km.'],
      ['hand', 'Massage', 'Right next door. We are happy to book an appointment for you.'],
      ['nosmoke', 'Non-smoking house', 'No smoking inside the house. Outside in the garden is fine.']
    ],
    saunaTitul: 'Finnish sauna',
    saunaUvod: 'In the basement, with a lounge and shower. Private, included in your stay, no booking needed.',
    sauna: [
      ['power', 'Switching on', 'Switch the sauna on by hand, right downstairs in the sauna. It deliberately cannot be switched on remotely – for safety.'],
      ['clock', 'Heating up', 'The sauna takes about half an hour to heat up.'],
      ['shower', 'Before the sauna', 'Shower and dry off. Always sit and lie on a towel.'],
      ['timer', 'One round', '8–15 minutes, as long as you feel good. Then cool down and rest at least as long.'],
      ['water', 'Drink water', 'Drink water between rounds. Save the alcohol for later.'],
      ['kids', 'Children', 'Children only with an adult.']
    ],
    doporuceni: 'Our recommendations',
    riziko: 'The sauna, pool, trampoline, playground, fire pit and everything else on the grounds are used at your own risk. Please keep an eye on children.',
    bazenTitul: 'Pool',
    bazenUvod: 'Covered and heated, lit in the evening. It can be locked.',
    bazen: [
      ['sun', 'Season', 'May to the end of September. Around 27 °C in summer; at the start and end of the season the water is usually cooler.'],
      ['clock', 'Open', 'Daily 6:00–22:00.'],
      ['lock', 'Locking', 'The pool can be locked. When nobody is there, please lock it – especially because of children.'],
      ['kids', 'Children', 'Children in the pool only under adult supervision.']
    ],
    bazenMimoText: 'Closed out of season now. We open again in May.',
    vyletyTitul: 'Trips nearby',
    vyletySub: '{n} tried-and-tested tips. Pick a trip and scan the QR code with your phone.',
    filtry: { vse: 'All', deti: 'With kids', dest: 'Rainy day', pesky: 'On foot', vyhledy: 'Views & hikes', kultura: 'Culture', voda: 'Swimming', adrenalin: 'Adrenaline' },
    pesky: 'on foot', autem: 'min by car',
    otevreno: 'Opening hours', cena: 'Price',
    qrMapa: 'Scan with your phone', qrMapaSub: 'route in Mapy.cz',
    qrWeb: 'Scan with your phone', qrWebSub: 'website',
    zadneVylety: 'Nothing for this choice right now.',
    pocasiTitul: 'Weather in Svoboda nad Úpou',
    pocasiSub: 'Forecast by yr.no, updated twice a day.',
    pocasiNic: 'The forecast could not be loaded right now.',
    dny: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    dnyK: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    mesice: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    vitr: 'wind', srazky: 'rain',
    wx: { clear: 'clear', fair: 'fair', partly: 'partly cloudy', cloudy: 'cloudy', fog: 'fog', showers: 'showers', rain: 'rain', snow: 'snow', sleet: 'sleet', thunder: 'thunderstorms' },
    okoliTitul: 'Shops & help',
    nakupy: 'Groceries', zdravi: 'Pharmacy & health', sluzby: 'Fuel',
    overit: 'We recommend checking the opening hours in advance.',
    distWalk: 'on foot', dist3: '~3 min by car', dist11: '~11 min by car', dist12: '~12 min by car', dist14: '~14 min by car', dist6jl: '~6 min by car · Janské Lázně',
    hDaily22: 'Daily 7:00–22:00', hDaily20: 'Daily 7:00–20:00', hLidl: 'Approx. 7:00–22:00 daily', hMartin: 'Daily 6:00–20:00',
    hCoop: 'Open 24/7 (self-service outside staffed hours)', nMartin: 'The nearest shop, right in Svoboda.',
    hLekarna: 'Mon–Fri 8:00–12:00 & 13:00–17:00, closed at weekends', hNemocnice: 'Emergency room 24/7 (incl. children)',
    t112: 'Emergency line', v112: 'The single European emergency number. Works with no credit and in your own language – ambulance, fire service and police.',
    mobilTitul: 'To your phone',
    mobilSub: 'Scan the QR code with your phone camera.',
    qrPlanovac: 'Trip planner', qrPlanovacSub: 'trips by weather and children’s age',
    qrInfo: 'Practical info', qrInfoSub: 'shops, pharmacy, contacts',
    qrApp: 'Villa Rudolf app', qrAppSub: '',
    offline: 'No internet – showing the saved version.'
  },

  pl: {
    menu: { home: 'Witajcie', dum: 'Dom', sauna: 'Sauna', bazen: 'Basen', vylety: 'Wycieczki', pocasi: 'Pogoda', okoli: 'Zakupy i pomoc', mobil: 'Na telefon' },
    hint: 'Strzałkami wybierajcie, OK otwiera, Wstecz wraca.',
    vitejte: 'Witajcie',
    vitejteSub: 'Cała Villa Rudolf jest teraz tylko wasza. Tu znajdziecie wszystko o domu, saunie, basenie i wycieczkach w okolicy.',
    dnes: 'Dziś',
    dnesSeHodi: 'Dziś polecamy',
    vse: 'Wszystkie wycieczki',
    odjezd: 'Wyjazd', odjezdV: 'do 10:00',
    klid: 'Cisza nocna', klidV: 'od 22:00',
    saunaKratce: 'W cenie, bez rezerwacji',
    saunaNahrati: 'nagrzewa się ok. 30 min',
    bazenOtevreno: 'Otwarte do 22:00',
    bazenRano: 'Otwiera o 6:00',
    bazenMimo: 'Poza sezonem',
    bazenMimoV: 'otwieramy w maju',
    dum: [
      ['clock', 'Przyjazd i wyjazd', 'Przyjazd od 15:00, wyjazd do 10:00.'],
      ['moon', 'Cisza nocna', 'Po 22:00 prosimy o ciszę ze względu na bliskich sąsiadów. W ogrodzie bez głośników, wieczorem bez muzyki. Rozmowy przy ognisku do późna są w porządku.'],
      ['thermo', 'Ogrzewanie', 'Każdy pokój i każda łazienka ma własny termostat.'],
      ['kitchen', 'Dwie kuchnie', 'Obie z piekarnikiem, zmywarką i kompletem naczyń. Na parterze dodatkowo dwie mikrofalówki, chłodziarka do wina i Nespresso, w apartamencie Suite mikrofalówka i drugie Nespresso.'],
      ['wash', 'Pranie', 'Pralka jest w łazience Pokoju 4 na 1. piętrze. Jest żelazko, suszarki do włosów są w łazienkach.'],
      ['ski', 'Narciarnia', 'W piwnicy. Buty wyschną w niej przez noc.'],
      ['grill', 'Altana i grille', 'Altana dla 20 osób z dwoma dużymi grillami elektrycznymi. Grillować można także w deszczu i śniegu.'],
      ['fire', 'Ognisko', 'Palenisko ze ścianą z gabionów dla całej grupy. Światła w ogrodzie po zmroku włączają się same.'],
      ['kids', 'Dla dzieci', 'Plac zabaw z drabinkami, zjeżdżalnią, huśtawkami i elementami linowymi, trampolina i tenis stołowy.'],
      ['car', 'Parking', 'Bezpłatny na posesji za bramą, wygodnie dla 7 aut.'],
      ['bus', 'Skibus', 'Przystanek 200 m od bramy, bezpłatny. Stoki w Svobodzie 1,9 km, Černá hora i Janské Lázně 4 km.'],
      ['hand', 'Masażysta', 'Tuż obok domu. Chętnie umówimy dla was termin.'],
      ['nosmoke', 'Dom dla niepalących', 'W domu się nie pali. Na zewnątrz w ogrodzie można.']
    ],
    saunaTitul: 'Sauna fińska',
    saunaUvod: 'W piwnicy, z przedsionkiem i prysznicem. Tylko dla was, w cenie pobytu, bez rezerwacji.',
    sauna: [
      ['power', 'Włączanie', 'Saunę włączacie ręcznie, na dole w saunie. Zdalnie włączyć się jej celowo nie da – ze względów bezpieczeństwa.'],
      ['clock', 'Nagrzewanie', 'Sauna nagrzewa się mniej więcej pół godziny.'],
      ['shower', 'Przed sauną', 'Weźcie prysznic i wytrzyjcie się. Siedźcie i leżcie zawsze na ręczniku.'],
      ['timer', 'Jedna runda', '8–15 minut, zależnie od samopoczucia. Potem schłodźcie się i odpoczywajcie co najmniej tyle samo.'],
      ['water', 'Pijcie wodę', 'Między rundami pijcie wodę. Alkohol zostawcie na później.'],
      ['kids', 'Dzieci', 'Dzieci do sauny tylko z dorosłym.']
    ],
    doporuceni: 'Polecamy',
    riziko: 'Z sauny, basenu, trampoliny, placu zabaw, ogniska i wszystkiego innego na posesji korzystacie na własną odpowiedzialność. Prosimy pilnować dzieci.',
    bazenTitul: 'Basen',
    bazenUvod: 'Zadaszony i podgrzewany, wieczorem oświetlony. Można go zamknąć na klucz.',
    bazen: [
      ['sun', 'Sezon', 'Od maja do końca września. Latem około 27 °C, na początku i na końcu sezonu woda bywa chłodniejsza.'],
      ['clock', 'Otwarte', 'Codziennie 6:00–22:00.'],
      ['lock', 'Zamykanie', 'Basen można zamknąć. Gdy nikogo przy nim nie ma, zamknijcie go proszę – zwłaszcza ze względu na dzieci.'],
      ['kids', 'Dzieci', 'Dzieci w basenie tylko pod opieką dorosłych.']
    ],
    bazenMimoText: 'Teraz poza sezonem zamknięty. Otwieramy znów w maju.',
    vyletyTitul: 'Wycieczki w okolicy',
    vyletySub: '{n} sprawdzonych propozycji. Wybierzcie wycieczkę i zeskanujcie kod QR telefonem.',
    filtry: { vse: 'Wszystkie', deti: 'Z dziećmi', dest: 'Na deszcz', pesky: 'Pieszo z domu', vyhledy: 'Widoki i szlaki', kultura: 'Kultura', voda: 'Kąpiel', adrenalin: 'Adrenalina' },
    pesky: 'pieszo', autem: 'min samochodem',
    otevreno: 'Godziny otwarcia', cena: 'Cena',
    qrMapa: 'Zeskanujcie telefonem', qrMapaSub: 'trasa w Mapy.cz',
    qrWeb: 'Zeskanujcie telefonem', qrWebSub: 'strona www',
    zadneVylety: 'Na ten wybór teraz nic nie mamy.',
    pocasiTitul: 'Pogoda w Svobodzie nad Úpą',
    pocasiSub: 'Prognoza yr.no, aktualizowana dwa razy dziennie.',
    pocasiNic: 'Nie udało się teraz wczytać prognozy.',
    dny: ['niedziela', 'poniedziałek', 'wtorek', 'środa', 'czwartek', 'piątek', 'sobota'],
    dnyK: ['nd', 'pn', 'wt', 'śr', 'cz', 'pt', 'sb'],
    mesice: ['stycznia', 'lutego', 'marca', 'kwietnia', 'maja', 'czerwca', 'lipca', 'sierpnia', 'września', 'października', 'listopada', 'grudnia'],
    vitr: 'wiatr', srazky: 'opady',
    wx: { clear: 'bezchmurnie', fair: 'prawie bezchmurnie', partly: 'częściowe zachmurzenie', cloudy: 'pochmurno', fog: 'mgła', showers: 'przelotne opady', rain: 'deszcz', snow: 'śnieg', sleet: 'deszcz ze śniegiem', thunder: 'burze' },
    okoliTitul: 'Zakupy i pomoc',
    nakupy: 'Zakupy', zdravi: 'Apteka i zdrowie', sluzby: 'Paliwo',
    overit: 'Godziny otwarcia zalecamy sprawdzić z wyprzedzeniem.',
    distWalk: 'pieszo', dist3: '~3 min samochodem', dist11: '~11 min samochodem', dist12: '~12 min samochodem', dist14: '~14 min samochodem', dist6jl: '~6 min samochodem · Janské Lázně',
    hDaily22: 'Codziennie 7:00–22:00', hDaily20: 'Codziennie 7:00–20:00', hLidl: 'Ok. 7:00–22:00 codziennie', hMartin: 'Codziennie 6:00–20:00',
    hCoop: 'Nonstop, 7 dni w tygodniu (poza godzinami z obsługą samoobsługowo)', nMartin: 'Najbliższy sklep, w samej Svobodzie.',
    hLekarna: 'Pon–pt 8:00–12:00 i 13:00–17:00, w weekend zamknięte', hNemocnice: 'Pogotowie non-stop (także dziecięce)',
    t112: 'Numer alarmowy', v112: 'Jednolity europejski numer alarmowy. Działa bez środków na koncie i w obcym języku – pogotowie, straż i policja.',
    mobilTitul: 'Na telefon',
    mobilSub: 'Zeskanujcie kod QR aparatem telefonu.',
    qrPlanovac: 'Planer wycieczek', qrPlanovacSub: 'wycieczki według pogody i wieku dzieci',
    qrInfo: 'Praktyczne informacje', qrInfoSub: 'zakupy, apteka, kontakty',
    qrApp: 'Aplikacja Villa Rudolf', qrAppSub: '',
    offline: 'Brak internetu – pokazuję zapisaną wersję.'
  }
};

/* Obchody a pomoc — jména a adresy jsou stejné ve všech jazycích. */
window.VR_OKOLI = {
  nakupy: [
    { n: 'Večerka Martin', a: '5. května 537, Svoboda nad Úpou', d: 'distWalk', h: 'hMartin', p: 'nMartin', ico: 'store' },
    { n: 'COOP 24/7', a: 'nám. Svobody 274, Janské Lázně', d: 'dist6jl', h: 'hCoop', ico: 'store' },
    { n: 'Kaufland', a: 'Horská 647, Trutnov', d: 'dist11', h: 'hDaily22', ico: 'cart' },
    { n: 'Albert', a: 'Žižkova 515, Trutnov', d: 'dist11', h: 'hDaily22', ico: 'cart' },
    { n: 'Penny Market', a: 'Horská 571, Trutnov', d: 'dist12', h: 'hDaily20', ico: 'cart' },
    { n: 'Lidl', a: 'Polská 432, Trutnov', d: 'dist14', h: 'hLidl', ico: 'cart' }
  ],
  zdravi: [
    { n: 'Lékárna U Černého orla', a: '5. května 424, Svoboda nad Úpou', d: 'distWalk', h: 'hLekarna', ico: 'pill' },
    { n: 'Oblastní nemocnice Trutnov', a: 'Maxima Gorkého 77, Trutnov', d: 'dist12', h: 'hNemocnice', ico: 'cross' }
  ],
  sluzby: [
    { n: 'Eurobit', a: 'Úpská 493, Svoboda nad Úpou', d: 'dist3', ico: 'fuel' }
  ]
};
